import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const root=fileURLToPath(new URL('.',import.meta.url)), PORT=process.env.PORT||5173, rooms=new Map(), sessions=new Map(), connections=new Map();
const prompts=['Rate pineapple on pizza (0 = crime, 10 = perfect).','How good is a spontaneous road trip?','How essential is coffee before noon?','Rate the joy of finding money in an old jacket.','How impressive is someone who can juggle?','How much does a rainy day improve a nap?','Rate the perfect amount of hot sauce.','How fun is getting lost in a new city?','How satisfying is peeling the plastic off a new gadget?','Rate breakfast for dinner.','How magical is a really good sunset?','How useful is knowing how to whistle loudly?','Rate the humble grilled cheese sandwich.','How brave is singing karaoke alone?','How fun is a board game night?','Rate the smell of fresh-cut grass.','How important is a perfectly timed meme?','Rate socks with sandals.','How exciting is a surprise day off?','How good is the first bite of a favorite meal?','Rate the art of making the perfect playlist.','How much personality does a houseplant add?','How fun is a midnight snack?','Rate the drama of a slow elevator.','How useful is having a photographic memory?','How satisfying is finishing a long to-do list?','Rate a nap that accidentally lasts three hours.','How much better is food outdoors?','How important is an aisle seat on a long flight?','Rate the sound of rain on a window.','How fun would it be to have a personal theme song?','Rate the confidence of wearing a bold outfit.','How enjoyable is browsing a bookstore with no plan?','How much should pancakes count as cake?','Rate the thrill of finding the shortest checkout line.','How fun is learning a useless fact?','How much does a dog improve a walk?','Rate the smell of a new book.','How exciting is receiving a package you forgot you ordered?','How important is a good group chat?','Rate dancing while cooking.','How fun is making up names for strangers’ pets?','How impressive is remembering someone’s coffee order?','Rate the mystery of a junk drawer.','How satisfying is a perfectly fitted bedsheet?','How much better is a movie with snacks?','Rate the confidence of someone wearing a cape in public.','How fun is taking the scenic route?','How important is a dramatic entrance?','Rate a sandwich cut diagonally.','How much joy comes from a perfectly timed high five?','How fun would a four-day weekend be?','Rate the tiny spoon in a dessert.','How useful is being able to parallel park?','How satisfying is solving a puzzle without hints?','Rate the smell of popcorn at a theater.','How fun is inventing a secret handshake?','How important is a comfortable hoodie?','Rate the suspense of waiting for toast to pop.','How much does a good nickname matter?'];
const colors=['#ff6b5f','#5b8def','#f7c948','#6ed7a5','#c084fc','#ef7ac8','#49c5b6','#ff9f43'];
const uid=()=>Math.random().toString(36).slice(2,10), code=()=>Array.from({length:4},()=>String.fromCharCode(65+Math.floor(Math.random()*26))).join('');
function snap(room,viewerId){return {type:'state',phase:room.phase,roomCode:room.code,hostId:room.hostId,viewerId,players:[...room.players.values()].map(p=>({id:p.id,name:p.name,color:p.color,score:p.score,connected:p.connected,submitted:!!room.answers[p.id]})),rounds:room.rounds,roundIndex:room.roundIndex,prompt:room.prompt,deadline:room.deadline,hostCanAdvance:room.hostId===viewerId,reveal:room.phase==='reveal'||room.phase==='final'?room.reveal:null}}
function push(room){for(const p of room.players.values()){const c=connections.get(p.id);if(c)c.write(`data: ${JSON.stringify(snap(room,p.id))}\n\n`)}}
function start(room){room.phase='answer';room.answers={};room.prompt=prompts[Math.floor(Math.random()*prompts.length)];room.deadline=Date.now()+45000;push(room);clearTimeout(room.timer);room.timer=setTimeout(()=>reveal(room),45000)}
function reveal(room){if(room.phase!=='answer')return;room.phase='reveal';clearTimeout(room.timer);const answers=Object.values(room.answers),avg=answers.length?answers.reduce((x,a)=>x+a.rating,0)/answers.length:0,max=answers.length>=3?Math.max(...answers.map(a=>Math.abs(a.rating-avg))):-1,wolves=answers.filter(a=>Math.abs(a.rating-avg)===max);const lone=max>=3&&wolves.length===1?wolves[0].id:null;room.reveal={average:avg,answers:answers.map(a=>{const error=Math.abs(a.guess-avg),read=Math.max(0,Math.round(10-2.5*error)),bull=error<=.25,wolf=a.id===lone,points=read+(bull?3:0)+(wolf?3:0);room.players.get(a.id).score+=points;return{...a,read,bull,wolf,points}})};push(room);clearTimeout(room.advance);room.advance=setTimeout(()=>next(room),20000)}
function next(room){if(room.phase!=='reveal')return;if(room.roundIndex+1>=room.rounds){room.phase='final';room.deadline=null;push(room)}else{room.roundIndex++;start(room)}}
function handle(msg,session){let room=rooms.get(session.roomCode),me=room?.players.get(session.playerId);if(!room||!me)return;if(msg.type==='start'&&room.hostId===me.id&&room.players.size>=2){room.roundIndex=0;room.players.forEach(p=>p.score=0);start(room)}if(msg.type==='answer'&&room.phase==='answer'&&!room.answers[me.id]){room.answers[me.id]={id:me.id,name:me.name,color:me.color,rating:Math.max(0,Math.min(10,Math.round(Number(msg.rating)))),guess:Math.max(0,Math.min(10,Math.round(Number(msg.guess)*2)/2))};push(room);if(Object.keys(room.answers).length===room.players.size)reveal(room)}if(msg.type==='next'&&room.hostId===me.id)next(room);if(msg.type==='again'&&room.hostId===me.id){room.phase='lobby';room.roundIndex=0;room.prompt='';room.reveal=null;room.players.forEach(p=>p.score=0);push(room)}}
async function body(req){let s='';for await(const c of req)s+=c;return JSON.parse(s||'{}')}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname==='/events'){const token=url.searchParams.get('token');const session=sessions.get(token);if(!session)return res.writeHead(401).end();res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','Access-Control-Allow-Origin':'*'});res.write(': connected\n\n');connections.set(session.playerId,res);const room=rooms.get(session.roomCode);if(room)res.write(`data: ${JSON.stringify(snap(room,session.playerId))}\n\n`);req.on('close',()=>{connections.delete(session.playerId);const p=room?.players.get(session.playerId);if(p){p.connected=false;if(room.hostId===p.id){const n=[...room.players.values()].find(x=>x.connected);if(n)room.hostId=n.id}push(room)}});return}if(url.pathname==='/api'){try{const msg=await body(req);if(msg.type==='create'){let c;do c=code();while(rooms.has(c));const room={code:c,hostId:null,players:new Map(),phase:'lobby',rounds:Number(msg.rounds)||5,roundIndex:0,prompt:'',answers:{},deadline:null};const p={id:uid(),name:String(msg.name).trim().slice(0,16),color:colors[0],score:0,connected:true};room.hostId=p.id;room.players.set(p.id,p);rooms.set(c,room);const token=randomUUID();sessions.set(token,{roomCode:c,playerId:p.id});return res.end(JSON.stringify({token,playerId:p.id,roomCode:c}))}if(msg.type==='join'){const c=String(msg.roomCode||'').toUpperCase(),room=rooms.get(c);if(!room)return res.writeHead(404).end(JSON.stringify({error:'Room not found.'}));let p=msg.playerId&&room.players.get(msg.playerId);if(!p){if(room.players.size>=8)return res.writeHead(400).end(JSON.stringify({error:'Room is full.'}));if([...room.players.values()].some(x=>x.name.toLowerCase()===String(msg.name).trim().toLowerCase()))return res.writeHead(400).end(JSON.stringify({error:'That name is already taken.'}));p={id:uid(),name:String(msg.name).trim().slice(0,16),color:colors[room.players.size%colors.length],score:0,connected:true};room.players.set(p.id,p)}p.connected=true;const token=randomUUID();sessions.set(token,{roomCode:c,playerId:p.id});return res.end(JSON.stringify({token,playerId:p.id,roomCode:c}))}const session=sessions.get(msg.token);if(!session)return res.writeHead(401).end();handle(msg,session);return res.end('{}')}catch(e){return res.writeHead(400).end(JSON.stringify({error:'Invalid request'}))}}const path=url.pathname==='/'?'/index.html':url.pathname;try{const data=await readFile(join(root,'public',path));const ext=extname(path);res.writeHead(200,{'Content-Type':ext==='.js'?'text/javascript':ext==='.css'?'text/css':'text/html'});res.end(data)}catch{res.writeHead(404).end('Not found')}});server.listen(PORT,()=>console.log(`Read the Room running at http://localhost:${PORT}`));
